# Generated by Django 5.0.3 on 2024-04-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('place_of_bitrh', models.CharField(max_length=60)),
                ('date_of_admission', models.DateTimeField(auto_now_add=True)),
                ('referral_number', models.CharField(max_length=60)),
                ('mother', models.CharField(max_length=60)),
                ('father', models.CharField(max_length=60)),
                ('legal_guardian', models.CharField(max_length=60)),
                ('siblings', models.IntegerField(default=0)),
                ('notes', models.TextField()),
            ],
        ),
    ]
