from .models import Children

def add_children():
    children_data = [
        {
            'name': 'Anna',
            'surname': 'Nowak',
            'date_of_birth': '2018-03-15',
            'place_of_bitrh': 'Kraków',
            'date_of_admission': '2022-01-10 09:00:00',
            'referral_number': '789012',
            'mother': 'Maria Nowak',
            'father': 'Piotr Nowak',
            'legal_guardian': 'Tomasz Kowalski',  
            'siblings': 0,
            'notes': 'Anna jest naszym najmłodszym pacjentem.',
        },
        {
            'name': 'Mateusz',
            'surname': 'Kowalczyk',
            'date_of_birth': '2016-07-25',
            'place_of_bitrh': 'Warszawa',
            'date_of_admission': '2022-02-05 11:30:00',
            'referral_number': '345678',
            'mother': 'Anna Kowalczyk',
            'father': 'Adam Kowalczyk',
            'legal_guardian': 'Marta Wiśniewska',  
            'siblings': 2,
            'notes': 'Mateusz uwielbia zabawki z klocków.',
        },
        {
            'name': 'Kasia',
            'surname': 'Dąbrowska',
            'date_of_birth': '2019-11-10',
            'place_of_bitrh': 'Poznań',
            'date_of_admission': '2022-03-20 10:15:00',
            'referral_number': '234567',
            'mother': 'Magda Dąbrowska',
            'father': 'Tomasz Dąbrowski',
            'legal_guardian': 'Monika Lewandowska',  
            'siblings': 1,
            'notes': 'Kasia uwielbia spacery po parku.',
        },
        {
            'name': 'Piotrek',
            'surname': 'Woźniak',
            'date_of_birth': '2017-09-20',
            'place_of_bitrh': 'Gdańsk',
            'date_of_admission': '2022-04-02 14:00:00',
            'referral_number': '456789',
            'mother': 'Aleksandra Woźniak',
            'father': 'Kamil Woźniak',
            'legal_guardian': 'Ewa Zając',  
            'siblings': 0,
            'notes': 'Piotrek lubi malować obrazki.',
        },
        {
            'name': 'Julia',
            'surname': 'Kaczmarek',
            'date_of_birth': '2018-12-05',
            'place_of_bitrh': 'Łódź',
            'date_of_admission': '2022-05-15 13:45:00',
            'referral_number': '567890',
            'mother': 'Karolina Kaczmarek',
            'father': 'Bartosz Kaczmarek',
            'legal_guardian': 'Jolanta Nowak',  
            'siblings': 2,
            'notes': 'Julia uwielbia czytać bajki.',
        },
        {
        'name': 'Maciek',
        'surname': 'Wojciechowski',
        'date_of_birth': '2017-05-12',
        'place_of_bitrh': 'Wrocław',
        'date_of_admission': '2022-06-20 08:30:00',
        'referral_number': '678901',
        'mother': 'Agnieszka Wojciechowska',
        'father': 'Marcin Wojciechowski',
        'legal_guardian': 'Monika Kowalczyk', 
        'siblings': 1,
        'notes': 'Maciek lubi grać w piłkę nożną.',
    },
    {
        'name': 'Zuzia',
        'surname': 'Nowakowska',
        'date_of_birth': '2019-08-28',
        'place_of_bitrh': 'Katowice',
        'date_of_admission': '2022-07-10 10:00:00',
        'referral_number': '789012',
        'mother': 'Magdalena Nowakowska',
        'father': 'Krzysztof Nowakowski',
        'legal_guardian': 'Wojciech Jankowski',  
        'siblings': 0,
        'notes': 'Zuzia uwielbia zwierzęta.',
    },
    {
        'name': 'Ola',
        'surname': 'Jasińska',
        'date_of_birth': '2018-02-14',
        'place_of_bitrh': 'Szczecin',
        'date_of_admission': '2022-08-05 11:45:00',
        'referral_number': '890123',
        'mother': 'Aneta Jasińska',
        'father': 'Tadeusz Jasiński',
        'legal_guardian': 'Katarzyna Kaczmarek',  
        'siblings': 2,
        'notes': 'Ola lubi rysować i malować.',
    },
    {
        'name': 'Michał',
        'surname': 'Lis',
        'date_of_birth': '2016-11-30',
        'place_of_bitrh': 'Gdynia',
        'date_of_admission': '2022-09-15 12:30:00',
        'referral_number': '901234',
        'mother': 'Ewa Lis',
        'father': 'Paweł Lis',
        'legal_guardian': 'Anna Lewicka',  
        'siblings': 1,
        'notes': 'Michał uwielbia grać na pianinie.',
    },
    {
        'name': 'Kacper',
        'surname': 'Szymański',
        'date_of_birth': '2017-07-18',
        'place_of_bitrh': 'Kraków',
        'date_of_admission': '2022-10-20 13:15:00',
        'referral_number': '012345',
        'mother': 'Małgorzata Szymańska',
        'father': 'Adam Szymański',
        'legal_guardian': 'Wioletta Wiśniewska', 
        'siblings': 0,
        'notes': 'Kacper uwielbia zabawki samochodowe.',
    },
    ]

    for data in children_data:
        Children.objects.create(**data)
